name: acceptance_act
description: Acceptance Act desktop application
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0
  flutter_lints: ^1.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  file_picker: ^8.0.0
  excel: ^4.0.2
  shared_preferences: ^2.2.2
  path_provider: ^2.0.15

flutter:
  uses-material-design: true
